const AssistErrorType = {
  USER_NOT_EXISTS: 30001, // 用户不存在
  PLAN_NOT_EXIST: 30101, // 会议不存在
  MEETING_IN_PROGRESS: 30102, // 会议正在进行中
  MEETING_NOT_IN_PROGRESS: 30103, // 会议未进行
  CANCEL_PLAN_PERMISSION_DENIED: 30104, // 没有权限取消会议
  CLOSE_PLAN_PERMISSION_DENIED: 30105, // 没有权限关闭会议
  MEETING_ALREADY_CANCELLED: 30106, // 会议已取消
  MEETING_ALREADY_FINISHED: 30107, // 会议已结束
  MEETING_IN_PROGRESS_CANNOT_MODIFY: 30108, // 会议进行中不能修改
  LONGTIME_MEETING_CAN_NOT_MODIFY: 30109, // 不能修改长期会议
  YOU_CAN_MODIFY_ONLY_MEETINGS_THAT_HAVE_NOT_STARTED: 30110, // 只能修改未开始的会议
  THE_START_TIME_MUST_BE_LATER_THAN_THE_CURRENT_TIME: 30111, // 开始时间必须晚于当前时间
  THE_END_TIME_MUST_BE_AFTER_THE_START_TIME: 30112, // 结束时间必须晚于开始时间
  MEETING_IS_OVERDUE: 30113, // 会议已过期
  MEETING_IS_FULL: 30116, // 会议人数已满
  UPLOAD_SCREENSHOT_PERMISSION_DENIED: 30201, // 没有权限上传截图
  QUERY_SCREENSHOT_PERMISSION_DENIED: 30202, // 没有权限查询截图
  UPLOAD_RECORD_PERMISSION_DENIED: 30301, // 没有权限上传录制文件
  QUERY_RECORD_PERMISSION_DENIED: 30302, // 没有权限查询录制文件
  MEETING_NOT_EXIST_30401: 30401, // 会议不存在
  OTHER_CLIENT_JOINED_MEETING: 30402, // 其他客户端已加入会议
  OTHER_CLIENT_IN_MEETING: 30403, // 其他客户端正在会议中
};

export default AssistErrorType;
